//! Contracts: generated from the economy and faction war, never from thin
//! air.
//!
//! A contract reserves real employer funds at creation (escrow out of the
//! treasury) and points at real targets: an existing convoy, formation,
//! asset, stockpile, or physical cargo. There is no contract enemy that does
//! not exist.
//!
//! TODO(generation): contracts generated by faction AI from TO&E shortages,
//! production bottlenecks, and strategic goals — this module is the typed
//! substrate that generator will emit into.
//!
//! [`World::settle_salvage`] transfers real wreck assets and lots to the
//! contractor per the negotiated [`SalvageTerms`] once a contract has
//! completed, respecting the employer veto list and tonnage cap, and
//! flagging illegal-legal-status goods so the game layer can enforce
//! consequences later (docket: legal metadata must survive salvage).

use crate::actors::Credits;
use crate::events::EventKind;
use crate::goods::LotState;
use crate::ids::*;
use crate::world::World;
use crate::SimError;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContractTarget {
    Convoy(ConvoyId),
    Formation(FormationId),
    Asset(AssetId),
    Stockpile(StockpileId),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ContractObjective {
    /// First archetype: go here, attack this enemy, radio back.
    AttackTarget {
        target: ContractTarget,
        report_back_to: LocationId,
    },
    /// Escort a real convoy.
    EscortConvoy { convoy: ConvoyId },
    /// Haul real cargo between real sites.
    HaulCargo {
        lots: Vec<LotId>,
        from: LocationId,
        to: LocationId,
    },
}

/// One item in an employer's salvage approval list.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetOrLot {
    Asset(AssetId),
    Lot(LotId),
}

/// Salvage is negotiated before the contract (docket: Contracts).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SalvageTerms {
    /// Contractor's share of salvage value, 0–100.
    pub contractor_share_pct: u8,
    /// Employer may veto specific equipment.
    pub employer_veto: bool,
    /// Optional cap on salvage tonnage.
    pub tonnage_cap: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ContractState {
    Open,
    Accepted { by: ActorId },
    /// `by` is retained so salvage can settle against the right contractor
    /// after completion.
    Completed { by: ActorId },
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Contract {
    pub id: ContractId,
    pub employer: ActorId,
    pub objective: ContractObjective,
    /// Real credits held out of the employer's treasury until settlement.
    pub escrowed_payment: Credits,
    pub salvage: SalvageTerms,
    pub issued_day: u64,
    pub state: ContractState,
}

impl World {
    /// Issue a contract. Validates that every referenced target physically
    /// exists and escrows the payment from the employer's treasury — an
    /// employer that cannot pay cannot post the contract.
    pub fn issue_contract(
        &mut self,
        employer: ActorId,
        objective: ContractObjective,
        payment: Credits,
        salvage: SalvageTerms,
    ) -> Result<ContractId, SimError> {
        if payment <= 0 {
            return Err(SimError::InvalidQuantity);
        }
        match &objective {
            ContractObjective::AttackTarget { target, report_back_to } => {
                self.validate_target(*target)?;
                if !self.locations.contains_key(report_back_to) {
                    return Err(SimError::UnknownLocation(*report_back_to));
                }
            }
            ContractObjective::EscortConvoy { convoy } => {
                if !self.convoys.contains_key(convoy) {
                    return Err(SimError::UnknownConvoy(*convoy));
                }
            }
            ContractObjective::HaulCargo { lots, from, to } => {
                for lot in lots {
                    if !self.lots.contains_key(lot) {
                        return Err(SimError::UnknownLot(*lot));
                    }
                }
                if !self.locations.contains_key(from) {
                    return Err(SimError::UnknownLocation(*from));
                }
                if !self.locations.contains_key(to) {
                    return Err(SimError::UnknownLocation(*to));
                }
            }
        }
        self.debit(employer, payment)?;
        let id = ContractId(self.alloc());
        let issued_day = self.clock.day;
        self.contracts.insert(
            id,
            Contract {
                id,
                employer,
                objective,
                escrowed_payment: payment,
                salvage,
                issued_day,
                state: ContractState::Open,
            },
        );
        self.push_event(EventKind::ContractIssued {
            contract: id,
            employer,
            escrow: payment,
        });
        Ok(id)
    }

    pub fn accept_contract(&mut self, contract: ContractId, contractor: ActorId) -> Result<(), SimError> {
        if !self.actors.contains_key(&contractor) {
            return Err(SimError::UnknownActor(contractor));
        }
        let c = self
            .contracts
            .get_mut(&contract)
            .ok_or(SimError::UnknownContract(contract))?;
        if c.state != ContractState::Open {
            return Err(SimError::InvalidState("contract is not open".into()));
        }
        if c.employer == contractor {
            return Err(SimError::InvalidState("employer cannot accept own contract".into()));
        }
        c.state = ContractState::Accepted { by: contractor };
        self.push_event(EventKind::ContractAccepted {
            contract,
            contractor,
        });
        Ok(())
    }

    /// Settle a completed contract: escrow pays out to the contractor, but
    /// only once the objective is actually proven true against live state —
    /// cargo really at its destination, an escorted convoy really arrived.
    /// `AttackTarget` contracts cannot yet be proven this way (there is no
    /// combat resolution to check against) and still complete on the
    /// caller's assertion; every other objective is checked for real.
    pub fn complete_contract(&mut self, contract: ContractId) -> Result<(), SimError> {
        self.verify_contract_outcome(contract)?;
        let (contractor, payout) = {
            let c = self
                .contracts
                .get_mut(&contract)
                .ok_or(SimError::UnknownContract(contract))?;
            let ContractState::Accepted { by } = c.state else {
                return Err(SimError::InvalidState("contract is not accepted".into()));
            };
            let payout = c.escrowed_payment;
            c.escrowed_payment = 0;
            c.state = ContractState::Completed { by };
            (by, payout)
        };
        self.credit(contractor, payout)?;
        self.push_event(EventKind::ContractCompleted {
            contract,
            payout,
        });
        Ok(())
    }

    /// Check the objective against live world state before allowing payout.
    fn verify_contract_outcome(&self, contract: ContractId) -> Result<(), SimError> {
        let c = self
            .contracts
            .get(&contract)
            .ok_or(SimError::UnknownContract(contract))?;
        match &c.objective {
            ContractObjective::HaulCargo { lots, to, .. } => {
                for lot in lots {
                    let l = self.lots.get(lot).ok_or(SimError::UnknownLot(*lot))?;
                    if self.resolve_site(l.location) != Some(*to) {
                        return Err(SimError::ContractNotFulfilled(contract));
                    }
                }
                Ok(())
            }
            ContractObjective::EscortConvoy { convoy } => {
                let cv = self.convoys.get(convoy).ok_or(SimError::UnknownConvoy(*convoy))?;
                match cv.state {
                    crate::convoys::ConvoyState::Arrived { .. }
                    | crate::convoys::ConvoyState::Disbanded => Ok(()),
                    _ => Err(SimError::ContractNotFulfilled(contract)),
                }
            }
            ContractObjective::AttackTarget { target, .. } => match target {
                ContractTarget::Asset(a) => {
                    let asset = self.assets.get(a).ok_or(SimError::UnknownAsset(*a))?;
                    let ContractState::Accepted { by } = c.state else {
                        return Err(SimError::InvalidState("contract is not accepted".into()));
                    };
                    if asset.condition_pct == 0 || asset.owner == by {
                        Ok(())
                    } else {
                        Err(SimError::ContractNotFulfilled(contract))
                    }
                }
                ContractTarget::Formation(f) => {
                    let formation = self.formations.get(f).ok_or(SimError::UnknownFormation(*f))?;
                    let still_fighting = formation
                        .assets
                        .iter()
                        .any(|a| self.assets.get(a).map(|x| x.condition_pct > 0).unwrap_or(false));
                    if still_fighting {
                        Err(SimError::ContractNotFulfilled(contract))
                    } else {
                        Ok(())
                    }
                }
                // TODO(combat): convoy interception and stockpile raiding
                // are different combat shapes than site-vs-site formation
                // battles; these objectives still complete on assertion.
                ContractTarget::Convoy(_) | ContractTarget::Stockpile(_) => Ok(()),
            },
        }
    }

    /// Settle salvage against a completed contract's negotiated terms.
    /// Transfers real assets and real lot quantities from whoever currently
    /// owns them to the contractor, honoring the employer veto list (if
    /// vetoing, only items in `approved` transfer) and the tonnage cap
    /// (total units transferred, assets counted as one unit each — a
    /// placeholder until commodities carry real per-unit mass). Any
    /// non-`Legitimate` legal status transferred is flagged so the game
    /// layer can react (bounty, faction heat, contraband seizure) later.
    pub fn settle_salvage(
        &mut self,
        contract: ContractId,
        assets: &[AssetId],
        lots: &[(LotId, u64)],
        approved: Option<&[AssetOrLot]>,
    ) -> Result<(), SimError> {
        let c = self
            .contracts
            .get(&contract)
            .ok_or(SimError::UnknownContract(contract))?
            .clone();
        let ContractState::Completed { by: contractor } = c.state else {
            return Err(SimError::InvalidState("salvage settles only after completion".into()));
        };

        let is_approved = |item: AssetOrLot| -> bool {
            match (&c.salvage.employer_veto, approved) {
                (false, _) => true,
                (true, Some(list)) => list.contains(&item),
                (true, None) => false,
            }
        };

        let mut total_units: u64 = 0;
        for &asset in assets {
            if !is_approved(AssetOrLot::Asset(asset)) {
                continue;
            }
            total_units = total_units.saturating_add(1);
        }
        for &(_, qty) in lots {
            total_units = total_units.saturating_add(qty);
        }
        if let Some(cap) = c.salvage.tonnage_cap {
            if total_units > cap {
                return Err(SimError::SalvageCapExceeded { contract, requested: total_units, cap });
            }
        }

        let mut moved_assets = Vec::new();
        for &asset in assets {
            if !is_approved(AssetOrLot::Asset(asset)) {
                continue;
            }
            self.transfer_asset(asset, contractor)?;
            moved_assets.push(asset);
        }

        let mut moved_lots = Vec::new();
        for &(lot, qty) in lots {
            if !is_approved(AssetOrLot::Lot(lot)) {
                continue;
            }
            let l = self.lots.get(&lot).ok_or(SimError::UnknownLot(lot))?;
            if l.state != LotState::Active {
                return Err(SimError::LotNotActive(lot));
            }
            let (full_qty, legal_status, owner) = (l.quantity, l.legal_status, l.owner);
            let piece = if qty >= full_qty {
                lot
            } else {
                self.split_lot(lot, qty)?
            };
            let from = owner;
            self.lots.get_mut(&piece).unwrap().owner = contractor;
            self.push_event(EventKind::LotOwnerChanged { lot: piece, from, to: contractor });
            if legal_status != crate::goods::LegalStatus::Legitimate {
                self.push_event(EventKind::IllegalSalvageFlagged { contract, lot: piece, legal_status });
            }
            moved_lots.push(piece);
        }

        self.push_event(EventKind::SalvageSettled {
            contract,
            contractor,
            assets: moved_assets,
            lots: moved_lots,
        });
        Ok(())
    }

    /// Cancel an open contract: escrow refunds to the employer.
    pub fn cancel_contract(&mut self, contract: ContractId) -> Result<(), SimError> {
        let (employer, refund) = {
            let c = self
                .contracts
                .get_mut(&contract)
                .ok_or(SimError::UnknownContract(contract))?;
            if c.state != ContractState::Open {
                return Err(SimError::InvalidState("only open contracts can be cancelled".into()));
            }
            let refund = c.escrowed_payment;
            c.escrowed_payment = 0;
            c.state = ContractState::Cancelled;
            (c.employer, refund)
        };
        self.credit(employer, refund)?;
        self.push_event(EventKind::ContractCancelled {
            contract,
            refunded: refund,
        });
        Ok(())
    }

    fn validate_target(&self, target: ContractTarget) -> Result<(), SimError> {
        match target {
            ContractTarget::Convoy(c) => {
                if !self.convoys.contains_key(&c) {
                    return Err(SimError::UnknownConvoy(c));
                }
            }
            ContractTarget::Formation(f) => {
                if !self.formations.contains_key(&f) {
                    return Err(SimError::UnknownFormation(f));
                }
            }
            ContractTarget::Asset(a) => {
                if !self.assets.contains_key(&a) {
                    return Err(SimError::UnknownAsset(a));
                }
            }
            ContractTarget::Stockpile(s) => {
                if !self.stockpiles.contains_key(&s) {
                    return Err(SimError::UnknownStockpile(s));
                }
            }
        }
        Ok(())
    }
}
